### PR TITLE
Fix weighted graph not working with Numerics other than integers and floats

### LINKED ISSUE #6: Graph Weights using BigDecimal fail
`GraphMatching::Weighted.weighted_edge?` checks for `Integer` and `Float` instead of `Numeric`, meaning other numerics (such as `BigDecimal`) fail.

### PR DESCRIPTION
**Pull request by BenjaminSchaaf**
Fixes #6

### CODE REVIEW

**Comment by jaredbeck** [comment]
Thanks Benjamin

**Comment by BenjaminSchaaf** [comment]
No worries, thank you very much for making this: Its saved me so much time! It would be great to have a new release of this gem with this fix (no rush from me though). If you're interested, I'm using the Maximum Weighted Matching for finding the best pairings of teams in a swiss tournament system.

**Comment by jaredbeck** [comment]
> No worries, thank you very much for making this: Its saved me so much time! It would be great to have a new release of this gem with this fix (no rush from me though).

Will do.

>  If you're interested, I'm using the Maximum Weighted Matching for finding the best pairings of teams in a swiss tournament system.

Awesome! That's exactly what I wrote it for, for baduk tournaments, but I never wrote the pairing software.

**Comment by jaredbeck** [comment]
Released as 0.2.0

**Comment by BenjaminSchaaf** [comment]
Awesome, thank you very much :)

**Comment by jaredbeck** [comment]
> .. I'm using the Maximum Weighted Matching for finding the best pairings of teams in a swiss tournament system.

What kind of tournament is it for?

**Comment by BenjaminSchaaf** [comment]
Its for the Australian Team Fortress 2 league "ozfortress" (https://warzone.ozfortress.com), its all open source here: https://github.com/ozfortress/citadel

**Pull request merged**
